export const HomeActionTypes = {
    FILTER_LOCATION: 'FILTER_LOCATION',
    FETCH_EMPLOYEES_START: 'FETCH_EMPLOYEES_START',
    FETCH_EMPLOYEES_SUCCESS: 'FETCH_EMPLOYEES_SUCCESS',
    FETCH_EMPLOYEES_FAILURE: 'FETCH_EMPLOYEES_FAILURE'
} 